### ISSUE TITLE
improve  http://remotestorage.io/get/

### ISSUE THREAD

**Issue by michielbdejong** [remotestorage/remotestorage.io#57]
see https://github.com/remotestorage/remotestorage.js/issues/476#issuecomment-28663360 for more details

**Comment by michielbdejong** [comment]
@skddc what made you close this? The 'learn more' link from the widget on https://grouptabs-staging.5apps.com/ now goes to https://remotestorage.io/ which is still the old site, and seems very far from that dedicated landing page you proposed.

**Comment by skddc** [comment]
> what made you close this?

The fact that this is but one part of the new site and we can open single issues when we have something to work from. Also, anyone can create a draft and do a pull request for a landing page at any time.

**Comment by michielbdejong** [comment]
OK, please only close issues if you or someone else fixed them.

**Comment by skddc** [comment]
This is a non-issue at the moment, and I'm basically the maintainer of this repo/website at the moment, so please let me manage the issues in the way that I see fit. Thanks!
