### ISSUE TITLE
review list of open source remoteStorage servers

### ISSUE THREAD

**Issue by michielbdejong** [remotestorage/remotestorage.io#67]
* add [reSite](https://github.com/michielbdejong/resite)
* maybe add [python-remotestorage (needs review)](https://github.com/relet/python-remotestorage/issues/1)
* make sure [php-remotestorage gets install instructions](https://github.com/fkooman/php-remoteStorage/issues/4)
* make sure [liquor-cabinet gets install instructions](https://github.com/5apps/liquor-cabinet/issues/44)
* update or remove [remotestorage-ruby](https://github.com/remotestorage/remotestorage-ruby/issues/8)
* update or remove [rs-serve](https://github.com/remotestorage/rs-serve)

**Comment by untitaker** [comment]
Per request of @skddc I copied that list to the wiki: https://wiki.remotestorage.io/Servers

**Comment by skddc** [comment]
@michielbdejong You want to add reSite to the wiki? Is it still something that people can use and depend on?

I added the unlisted ones to a new section for outdated servers: https://wiki.remotestorage.io/Servers#Outdated_solutions

**Comment by michielbdejong** [comment]
@skddc no, reSite is not actively maintained at the moment. Thanks for asking!

Actually just this week, I switched the last four sites I was hosting on my server (michielbdejong.com, unhosted.org, opentabs.net and useraddress.net) to static gh-pages hosting. I'll probably go back to self-hosting and indiewebbing in the future, and might revive reSite when I do, and if I do I'll update that wiki page.
