### ISSUE TITLE
publish docs from remotestorage.js /doc folder

### ISSUE THREAD

**Issue by michielbdejong** [remotestorage/remotestorage.io#71]
In the /doc folder of the remotestorage.js repo, there is a bunch of guides and other docs that never got published, neither on http://remotestorage.io/integrate/ nor on http://remotestorage.io/doc/code/files/remotestorage-js.html:
- [Caching in remotestorage.js](https://github.com/remotestorage/remotestorage.js/blob/master/doc/caching.md)
- [API (defining modules, using a module in your app, customization)](https://github.com/remotestorage/remotestorage.js/blob/master/doc/api.md)
- [Data format (node versions, auto-merge, caching strategies, keep/revert conflict events, implications for module design)](https://github.com/remotestorage/remotestorage.js/blob/master/doc/data-format.md)

**Comment by raucao** [comment]
https://remotestoragejs.readthedocs.io
