### ISSUE TITLE
[forums] Header overlayed by content in private message view when scrolling down

### ISSUE THREAD

**Issue by skddc** [remotestorage/remotestorage.io#77]

**Comment by skddc** [comment]
![screenshot from 2015-02-11 07 45 13](https://cloud.githubusercontent.com/assets/842/6146337/f228e91a-b1c1-11e4-88c2-57c2f469e54b.png)

**Comment by raucao** [comment]
Closing in favor of https://github.com/remotestorage/website/issues/20
