### ISSUE TITLE
[FORUMS] None of the three federated login options is working

### ISSUE THREAD

**Issue by stevenroose** [remotestorage/remotestorage.io#79]
I wanted to access the forums and login through a federated login. None of them worked; these are their errors:

* GitHub: Somehow the redirect to GitHub fails, giving this window
![](http://i.imgur.com/F4hKZJH.png)

* Google: Google no longer supports OpenID 2.0. This is probably due to an old version of the forum software that has not yet upgraded to OpenID Connect. [More info on this.](https://support.google.com/accounts/answer/6206245?p=openid&rd=1)

* Twitter: The Twitter OAuth page is shown, but the redict URL gives an SSL error.
![](http://i.imgur.com/ZYFdMdu.png)

I dont like entering account details, so I'll have to wait until I can access the forums...

**Comment by gregkare** [comment]
Hi,

I'm going to see if upgrading the forums fixes the GitHub and Twitter integrations. I'll need help to get a new Google OpenID Connect token

**Comment by skddc** [comment]
It's redirecting to port 80?

**Comment by gregkare** [comment]
It's weird, the callback URL is httpS but on port 80 so it's not a redirection, I tried to create a different Twitter app but it behaved the same

**Comment by skddc** [comment]
So Twitter is attaching the `:80`?

**Comment by gregkare** [comment]
That's what it looks like, my plan is to use a temporary discourse to try things out without restarting the remotestorage one all the time

**Comment by skddc** [comment]
Sounds like a good idea. :)

**Comment by skddc** [comment]
@gregkare anything new about this?

**Comment by gregkare** [comment]
I didn't have time to investigate more, I'll set up a temporary discourse in the next couple days

**Comment by gregkare** [comment]
@stevenroose It took a while but updating Discourse finally fixed it. Twitter and GitHub logins are working, can you confirm it's working for you?

Thanks, and sorry it took so long.

**Comment by stevenroose** [comment]
GitHub forms for me, thanks!

**Comment by skddc** [comment]
Persona and Google are working as well now. Closing issue.

@stevenroose Thanks for your patience. @gregkare++ for fixing this. :)
