### ISSUE TITLE
Let user select sandboxed directory to use?

### ISSUE THREAD

**Issue by akumpf** [remotestorage/remotestorage.io#80]
I think the ideas behind remotestorage are great, but from the user's perspective, it seems important to let the user choose which folder to grant access to.

For example, let's say I have a folder of notes that I want to open in a "unhosted" remotestorage app. I don't want to grant full access to all my files, only a particular folder (or in the most constrained case, just a single file). While a global naming approach works (assuming that my notes are stored in a folder called "notes"), it would be a lot better if I, as the user, could decide which folder/file to grant access for a particular app.

I've also posted this question more broadly for Google Drive and Dropbox here: http://stackoverflow.com/questions/30736664/directory-sandboxed-access-for-google-drive-dropbox-api-remotestorage-apps

If this is already in remotestorage and I somehow missed it, let me know! Otherwise, I hope this can serve as a formal feature request to make remotestorage even better. :)

**Comment by skddc** [comment]
Thanks for your request @akumpf! I've taken the liberty to move it to the appropriate repo, which is that of the specification of the remoteStorage protocol itself. Just follow that issue instead. :)
